#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/NotFound.cshtml")]
    public partial class _Views_Error_NotFound_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Error_NotFound_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Error\NotFound.cshtml"
  
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-8\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"jumbotron text-center\"");

WriteLiteral(">\r\n            <h1");

WriteLiteral(" class=\" text-center\"");

WriteLiteral("><div");

WriteLiteral(" class=\"text-info fa fa-warning\"");

WriteLiteral("></div></h1>\r\n            <small");

WriteLiteral(" class=\"text-info\"");

WriteLiteral(">خطا 404</small>\r\n            <h2");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">صفحه مورد نظر شما پیدا نشده است.</h2>\r\n            <small><p>یک متن راهنما برای " +
"کاربر که چرا به این صفحه اماده  است.</p></small>\r\n            <br><br><br><br><b" +
"r><br><br>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
