#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Applicant\Create.cshtml"
    using Decision.Common.Extentions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Applicant\Create.cshtml"
    using Decision.Common.HtmlHelpers;
    
    #line default
    #line hidden
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Applicant/Create.cshtml")]
    public partial class _Views_Applicant_Create_cshtml : System.Web.Mvc.WebViewPage<Decision.ViewModel.Applicant.AddApplicantViewModel>
    {
        public _Views_Applicant_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Applicant\Create.cshtml"
  
    ViewBag.Title = "درج متقاضی جدید";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Applicant\Create.cshtml"
 using (Html.BeginForm(MVC.Applicant.Create(), FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "createApplicantForm", enctype = "multipart/form-data" }))
{
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Applicant\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Applicant\Create.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Applicant\Create.cshtml"
Write(Html.HiddenFor(model => model.PhotoScan));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Applicant\Create.cshtml"
                                             
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Applicant\Create.cshtml"
Write(Html.HiddenFor(model => model.CopyOfBirthCertificateScan));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Applicant\Create.cshtml"
                                                              
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Applicant\Create.cshtml"
Write(Html.HiddenFor(model => model.CopyOfNationalCardScan));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Applicant\Create.cshtml"
                                                          


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 18 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.HelpAlert(Url.Content("~/Content/Images/lightbulb.png"),
                    "در صورت عمل نکردن دکمه ثبت،توجه داشته باشید که تمام اطلاعات را در تمام تب های موجود صحیح وارد کرده باشید",
                    "برای فایل های ضمیمه مربوط به متقاضی از امکان آپلود تصاویر یا اسکن  میتوانید بهره مند شوید."
           ));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-1\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'createApplicantForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-md\"");

WriteLiteral(">\r\n                        ثبت اطلاعات متقاضی\r\n                    </button>\r\n   " +
"             </div>\r\n\r\n            </div>\r\n            <hr");

WriteLiteral(" class=\"margin-bottom-5 margin-top-5\"");

WriteLiteral(" />\r\n            <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#baseInfo\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">اطلاعات پایه</a>\r\n                </li>\r\n                <li>\r\n                 " +
"   <a");

WriteLiteral(" href=\"#other\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">سایر اطلاعات</a>\r\n                </li>\r\n                \r\n                <li>\r" +
"\n                    <a");

WriteLiteral(" href=\"#files\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">فایل های ضمیمه</a>\r\n                </li>\r\n            </ul>\r\n            <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"baseInfo\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 53 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 55 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 56 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 60 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 62 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 63 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 68 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.NationalCode, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 70 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.NationalCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 71 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.NationalCode, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 75 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.BirthCertificateNumber, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 77 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.BirthCertificateNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 78 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthCertificateNumber, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 82 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 84 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.EditorFor(model => model.Gender, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 85 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 87 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.MarriageStatus, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 89 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.EditorFor(model => model.MarriageStatus, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 90 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.MarriageStatus, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 94 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.BirthPlaceState, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 96 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.DropDownListFor(model => model.BirthPlaceState,
                            Model.StatesForBirthPlace, "انتخاب استان محل تولد", new
                            {
                                @class = "form-control cascade",
                                data_tofill = "BirthPlaceCity",
                                data_lable = "انتخاب شهر محل تولد",
                                data_selects = "BirthPlaceCity",
                                data_url = Url.Action(MVC.City.GetCities())
                            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 105 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthPlaceState, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 107 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.BirthPlaceCity, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 109 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.DropDownListFor(model => model.BirthPlaceCity, Model.CitiesForBirthPlace, "انتخاب شهر محل تولد", new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 110 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthPlaceCity, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 114 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 116 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.EditorFor(model => model.BirthDate, MVC.Shared.Views.EditorTemplates.PersianDatePicker));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 117 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                    </div>\r\n                </div>\r" +
"\n                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"other\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 127 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.FatherName, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 129 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.FatherName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 130 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 134 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.Email, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 136 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 137 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Email, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 141 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.CellphoneNumber, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 143 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.CellphoneNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 144 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.CellphoneNumber, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 148 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 150 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 151 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.PhoneNumber, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 156 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.NumberIndispensable, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 158 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.NumberIndispensable));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 159 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.NumberIndispensable, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 164 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.MilitaryStatus, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 166 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.EditorFor(model => model.MilitaryStatus, new {@class = "form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 167 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.MilitaryStatus, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 169 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.MembershipType, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 171 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.EditorFor(model => model.MembershipType, new {@class = "form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 172 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.MembershipType, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 176 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.ServedEndOn, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 178 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.EditorFor(model => model.ServedEndOn, MVC.Shared.Views.EditorTemplates.PersianDatePicker));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 179 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.ServedEndOn, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 183 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.Gilder, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 185 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.Gilder));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 186 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Gilder, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 190 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 192 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.Nationality));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 193 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                    </div>\r\n                </div>\r" +
"\n                \r\n\r\n                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"files\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 205 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.CopyOfNationalCardFile, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 207 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.TextBoxFor(model => model.CopyOfNationalCardFile, new { type = "file", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"CopyOfNationalCardScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 14167), Tuple.Create("\"", 14267)
, Tuple.Create(Tuple.Create("", 14175), Tuple.Create("btn", 14175), true)
, Tuple.Create(Tuple.Create(" ", 14178), Tuple.Create("btn-primary", 14179), true)
, Tuple.Create(Tuple.Create("   ", 14190), Tuple.Create("btn-sm", 14193), true)
            
            #line 210 "..\..\Views\Applicant\Create.cshtml"
                                                                                      , Tuple.Create(Tuple.Create(" ", 14199), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 14200), false)
);

WriteLiteral(">\r\n");

            
            #line 211 "..\..\Views\Applicant\Create.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 211 "..\..\Views\Applicant\Create.cshtml"
                                         if (Model.CopyOfNationalCardScan.HasValue())
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                حذف فایل اسکن شده\r\n                       " +
"                 ");

WriteLiteral("\r\n");

            
            #line 216 "..\..\Views\Applicant\Create.cshtml"
                                        }
                                        else
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                افزودن اسکن\r\n                             " +
"           ");

WriteLiteral("\r\n");

            
            #line 222 "..\..\Views\Applicant\Create.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </button>\r\n                                </" +
"div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 227 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.CopyOfBirthCertificateFile, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 229 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.TextBoxFor(model => model.CopyOfBirthCertificateFile, new { type = "file", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"CopyOfBirthCertificateScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 15674), Tuple.Create("\"", 15774)
, Tuple.Create(Tuple.Create("", 15682), Tuple.Create("btn", 15682), true)
, Tuple.Create(Tuple.Create(" ", 15685), Tuple.Create("btn-primary", 15686), true)
, Tuple.Create(Tuple.Create("   ", 15697), Tuple.Create("btn-sm", 15700), true)
            
            #line 232 "..\..\Views\Applicant\Create.cshtml"
                                                                                          , Tuple.Create(Tuple.Create(" ", 15706), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 15707), false)
);

WriteLiteral(">\r\n");

            
            #line 233 "..\..\Views\Applicant\Create.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 233 "..\..\Views\Applicant\Create.cshtml"
                                         if (Model.CopyOfBirthCertificateScan.HasValue())
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                حذف فایل اسکن شده\r\n                       " +
"                 ");

WriteLiteral("\r\n");

            
            #line 238 "..\..\Views\Applicant\Create.cshtml"
                                        }
                                        else
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa  fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                افزودن اسکن\r\n                             " +
"           ");

WriteLiteral("\r\n");

            
            #line 244 "..\..\Views\Applicant\Create.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </button>\r\n                                </" +
"div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 249 "..\..\Views\Applicant\Create.cshtml"
                           Write(Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 251 "..\..\Views\Applicant\Create.cshtml"
                               Write(Html.TextBoxFor(model => model.PhotoFile, new { type = "file", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"PhotoScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 17135), Tuple.Create("\"", 17235)
, Tuple.Create(Tuple.Create("", 17143), Tuple.Create("btn", 17143), true)
, Tuple.Create(Tuple.Create(" ", 17146), Tuple.Create("btn-primary", 17147), true)
, Tuple.Create(Tuple.Create("   ", 17158), Tuple.Create("btn-sm", 17161), true)
            
            #line 254 "..\..\Views\Applicant\Create.cshtml"
                                                                         , Tuple.Create(Tuple.Create(" ", 17167), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 17168), false)
);

WriteLiteral(">\r\n");

            
            #line 255 "..\..\Views\Applicant\Create.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 255 "..\..\Views\Applicant\Create.cshtml"
                                         if (Model.PhotoScan.HasValue())
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                حذف فایل اسکن شده\r\n                       " +
"                 ");

WriteLiteral("\r\n");

            
            #line 260 "..\..\Views\Applicant\Create.cshtml"
                                        }
                                        else
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                افزودن اسکن\r\n                             " +
"           ");

WriteLiteral("\r\n");

            
            #line 266 "..\..\Views\Applicant\Create.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </button>\r\n                                </" +
"div>\r\n                            </div>\r\n                        </div>\r\n      " +
"              </div>\r\n                </div>\r\n            </div>\r\n        </div>" +
"\r\n    </div>\r\n");

            
            #line 276 "..\..\Views\Applicant\Create.cshtml"
}

            
            #line default
            #line hidden
DefineSection("Menu", () => {

WriteLiteral("\r\n");

            
            #line 278 "..\..\Views\Applicant\Create.cshtml"
    
            
            #line default
            #line hidden
            
            #line 278 "..\..\Views\Applicant\Create.cshtml"
      Html.RenderPartial(MVC.Shared.Views._ApplicantManagementsSidbarMenu);
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 281 "..\..\Views\Applicant\Create.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 282 "..\..\Views\Applicant\Create.cshtml"
Write(Scripts.Render("~/bundles/datePicker"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
