#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Applicant\Create.cshtml"
    using Decision.Common.Extentions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Applicant\Create.cshtml"
    using Decision.Common.HtmlHelpers;
    
    #line default
    #line hidden
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Applicant/Create.cshtml")]
    public partial class _Views_Applicant_Create_cshtml : System.Web.Mvc.WebViewPage<Decision.ViewModel.Applicant.AddApplicantViewModel>
    {
        public _Views_Applicant_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Applicant\Create.cshtml"
  
    ViewBag.Title = "درج متقاضی جدید";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Applicant\Create.cshtml"
 using (Html.BeginForm(MVC.Applicant.Create(), FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "createApplicantForm", enctype = "multipart/form-data" }))
{
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Applicant\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Applicant\Create.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Applicant\Create.cshtml"
Write(Html.HiddenFor(model=>model.PhotoScan));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Applicant\Create.cshtml"
                                           
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Applicant\Create.cshtml"
Write(Html.HiddenFor(model => model.CopyOfBirthCertificateScan));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Applicant\Create.cshtml"
                                                              
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Applicant\Create.cshtml"
Write(Html.HiddenFor(model => model.CopyOfNationalCardScan));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Applicant\Create.cshtml"
                                                          


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Views\Applicant\Create.cshtml"
           Write(Html.HelpAlert(Url.Content("~/Content/Images/lightbulb.png"),
                    "در صورت عمل نکردن دکمه ثبت،توجه داشته باشید که تمام اطلاعات را در تمام تب های موجود صحیح وارد کرده باشید",
                    "برای فایل های ضمیمه مربوط به متقاضی از امکان آپلود تصاویر یا اسکن  میتوانید بهره مند شوید."
           ));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-1\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'createApplicantForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-md\"");

WriteLiteral(">\r\n                ثبت اطلاعات متقاضی\r\n            </button>\r\n        </div>\r\n\r\n " +
"   </div>\r\n    <hr");

WriteLiteral(" class=\"margin-bottom-5 margin-top-5\"");

WriteLiteral("/>\r\n    <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#baseInfo\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">اطلاعات پایه</a>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#bank\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">اطلاعات بانکی</a>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#certificate\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">اطلاعات شغلی</a>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#trainingCourse\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">دوره کارآموزی</a>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#files\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">فایل های ضمیمه</a>\r\n        </li>\r\n    </ul>\r\n    <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"baseInfo\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 58 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.FirstName, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 60 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxFor(model => model.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 61 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.FirstName, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 65 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.LastName, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 67 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxFor(model => model.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 68 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.LastName, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 72 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.PersonnelCode, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 74 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxForLtr(model => model.PersonnelCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 75 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.PersonnelCode, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 79 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.NationalCode, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 81 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxForLtr(model => model.NationalCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 82 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.NationalCode, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 86 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.BirthCertificateNumber, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 88 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxForLtr(model => model.BirthCertificateNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 89 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.BirthCertificateNumber, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 93 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.Gender, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 95 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.EditorFor(model => model.Gender, new {@class = "form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 96 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Gender, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 98 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.MarriageStatus, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 100 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.EditorFor(model => model.MarriageStatus, new {@class = "form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 101 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.MarriageStatus, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 105 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.BirthPlaceState, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 107 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.DropDownListFor(model => model.BirthPlaceState,
                            Model.StatesForBirthPlace, "انتخاب استان محل تولد", new
                            {
                                @class = "form-control cascade",
                                data_tofill = "BirthPlaceCity",
                                data_lable = "انتخاب شهر محل تولد",
                                data_selects = "BirthPlaceCity",
                                data_url = Url.Action(MVC.City.GetCities())
                            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 116 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.BirthPlaceState, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 118 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.BirthPlaceCity, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 120 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.DropDownListFor(model => model.BirthPlaceCity, Model.CitiesForBirthPlace, "انتخاب شهر محل تولد", new {@class = "form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 121 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.BirthPlaceCity, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 125 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.BirthDate, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 127 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.EditorFor(model => model.BirthDate, MVC.Shared.Views.EditorTemplates.PersianDatePicker));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 128 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.BirthDate, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"bank\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 138 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.BankName, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 140 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxFor(model => model.BankName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 141 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.BankName, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 145 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.BankBranch, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 147 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxFor(model => model.BankBranch));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 148 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.BankBranch, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 152 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.AccountNumber, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 154 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxFor(model => model.AccountNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 155 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.AccountNumber, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"certificate\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 167 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.TrainingGPA, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 169 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.EditorFor(model => model.TrainingGPA));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 170 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.TrainingGPA, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 172 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.TrainigGrade, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 174 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxForNumber(model => model.TrainigGrade));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 175 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.TrainigGrade, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 179 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.CollegiateOrder, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 181 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxForNumber(model => model.CollegiateOrder));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 182 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.CollegiateOrder, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 184 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.OccupationalGroup, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 186 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxForNumber(model => model.OccupationalGroup));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 187 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.OccupationalGroup, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 191 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.OfficialYears, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 193 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxForNumber(model => model.OfficialYears));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 194 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.OfficialYears, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 196 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.CollegiateYears, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 198 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.NoAutoCompleteTextBoxForNumber(model => model.CollegiateYears));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 199 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.CollegiateYears, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 203 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.PositionId, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 205 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.DropDownListFor(model => model.PositionId, Model.Positions, new {@class = "form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 206 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.PositionId, "", new {@class = "text-danger"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    \r\n                    <div");

WriteLiteral(" class=\"col-md-4 col-md-offset-2\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 210 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.CheckBoxFor(model => model.IsClothed, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 211 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.LabelFor(a => a.IsClothed, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </div>\r\n  \r\n    <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"files\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 222 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.CopyOfNationalCardFile, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 224 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.TextBoxFor(model => model.CopyOfNationalCardFile, new {type = "file", @class = "form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"CopyOfNationalCardScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 13092), Tuple.Create("\"", 13192)
, Tuple.Create(Tuple.Create("", 13100), Tuple.Create("btn", 13100), true)
, Tuple.Create(Tuple.Create(" ", 13103), Tuple.Create("btn-primary", 13104), true)
, Tuple.Create(Tuple.Create("   ", 13115), Tuple.Create("btn-sm", 13118), true)
            
            #line 227 "..\..\Views\Applicant\Create.cshtml"
                                                                          , Tuple.Create(Tuple.Create(" ", 13124), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 13125), false)
);

WriteLiteral(">\r\n");

            
            #line 228 "..\..\Views\Applicant\Create.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 228 "..\..\Views\Applicant\Create.cshtml"
                             if (Model.CopyOfNationalCardScan.HasValue())
                            {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                 <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                 حذف فایل اسکن شده\r\n                      " +
"       ");

WriteLiteral("\r\n");

            
            #line 233 "..\..\Views\Applicant\Create.cshtml"
                            }
                            else
                            {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                 <i");

WriteLiteral(" class=\"fa fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                 افزودن اسکن\r\n                            " +
" ");

WriteLiteral("\r\n");

            
            #line 239 "..\..\Views\Applicant\Create.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </button>\r\n                    </div>\r\n                </" +
"div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 244 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.CopyOfBirthCertificateFile, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 246 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.TextBoxFor(model => model.CopyOfBirthCertificateFile, new {type = "file", @class = "form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"CopyOfBirthCertificateScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 14385), Tuple.Create("\"", 14485)
, Tuple.Create(Tuple.Create("", 14393), Tuple.Create("btn", 14393), true)
, Tuple.Create(Tuple.Create(" ", 14396), Tuple.Create("btn-primary", 14397), true)
, Tuple.Create(Tuple.Create("   ", 14408), Tuple.Create("btn-sm", 14411), true)
            
            #line 249 "..\..\Views\Applicant\Create.cshtml"
                                                                              , Tuple.Create(Tuple.Create(" ", 14417), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 14418), false)
);

WriteLiteral(">\r\n");

            
            #line 250 "..\..\Views\Applicant\Create.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 250 "..\..\Views\Applicant\Create.cshtml"
                             if (Model.CopyOfBirthCertificateScan.HasValue())
                            {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                 <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                 حذف فایل اسکن شده\r\n                      " +
"       ");

WriteLiteral("\r\n");

            
            #line 255 "..\..\Views\Applicant\Create.cshtml"
                            }
                            else
                            {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                 <i");

WriteLiteral(" class=\"fa  fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                 افزودن اسکن\r\n                            " +
" ");

WriteLiteral("\r\n");

            
            #line 261 "..\..\Views\Applicant\Create.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </button>\r\n                    </div>\r\n                </" +
"div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 266 "..\..\Views\Applicant\Create.cshtml"
               Write(Html.LabelFor(model => model.PhotoFile, htmlAttributes: new {@class = "control-label col-md-2"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 268 "..\..\Views\Applicant\Create.cshtml"
                   Write(Html.TextBoxFor(model => model.PhotoFile, new {type = "file", @class = "form-control"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"PhotoScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 15632), Tuple.Create("\"", 15732)
, Tuple.Create(Tuple.Create("", 15640), Tuple.Create("btn", 15640), true)
, Tuple.Create(Tuple.Create(" ", 15643), Tuple.Create("btn-primary", 15644), true)
, Tuple.Create(Tuple.Create("   ", 15655), Tuple.Create("btn-sm", 15658), true)
            
            #line 271 "..\..\Views\Applicant\Create.cshtml"
                                                             , Tuple.Create(Tuple.Create(" ", 15664), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 15665), false)
);

WriteLiteral(">\r\n");

            
            #line 272 "..\..\Views\Applicant\Create.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 272 "..\..\Views\Applicant\Create.cshtml"
                             if (Model.PhotoScan.HasValue())
                            {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                 <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                 حذف فایل اسکن شده\r\n                      " +
"       ");

WriteLiteral("\r\n");

            
            #line 277 "..\..\Views\Applicant\Create.cshtml"
                            }
                            else
                            {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                 <i");

WriteLiteral(" class=\"fa fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                 افزودن اسکن\r\n                            " +
" ");

WriteLiteral("\r\n");

            
            #line 283 "..\..\Views\Applicant\Create.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </button>\r\n                    </div>\r\n                </" +
"div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    </div>\r\n    </div>\r\n  " +
"  </div>\r\n");

            
            #line 293 "..\..\Views\Applicant\Create.cshtml"
}

            
            #line default
            #line hidden
DefineSection("Menu", () => {

WriteLiteral("\r\n");

            
            #line 295 "..\..\Views\Applicant\Create.cshtml"
    
            
            #line default
            #line hidden
            
            #line 295 "..\..\Views\Applicant\Create.cshtml"
      Html.RenderPartial(MVC.Shared.Views._ApplicantManagementsSidbarMenu);
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 298 "..\..\Views\Applicant\Create.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 299 "..\..\Views\Applicant\Create.cshtml"
Write(Scripts.Render("~/bundles/datePicker"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
