#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Applicant\Edit.cshtml"
    using Decision.Common.Extentions;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Applicant\Edit.cshtml"
    using Decision.Common.HtmlHelpers;
    
    #line default
    #line hidden
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Applicant/Edit.cshtml")]
    public partial class _Views_Applicant_Edit_cshtml : System.Web.Mvc.WebViewPage<Decision.ViewModel.Applicant.EditApplicantViewModel>
    {
        public _Views_Applicant_Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Applicant\Edit.cshtml"
  
    ViewBag.Title = "ویرایش متقاضی";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Applicant\Edit.cshtml"
 using (Html.BeginForm(MVC.Applicant.Edit(), FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "editApplicantForm", enctype = "multipart/form-data" }))
{
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Applicant\Edit.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Applicant\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.HiddenFor(model => model.PhotoScan));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Applicant\Edit.cshtml"
                                             
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.HiddenFor(model => model.CopyOfBirthCertificateScan));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Applicant\Edit.cshtml"
                                                              
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.HiddenFor(model => model.CopyOfNationalCardScan));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Applicant\Edit.cshtml"
                                                          



            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 22 "..\..\Views\Applicant\Edit.cshtml"
               Write(Html.HelpAlert(Url.Content("~/Content/Images/lightbulb.png"),
                        "در صورت عمل نکردن دکمه ثبت،توجه داشته باشید که تمام اطلاعات را در تمام تب های موجود صحیح وارد کرده باشید",

                        "برای فایل های ضمیمه مربوط به متقاضی از امکان آپلود تصاویر یا اسکن  میتوانید بهره مند شوید.",
                        "دقت کنید در صورت انتخاب فایل جدید،جایگزین فایل های جدید خواهد شد"
                        ));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-1\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'editApplicantForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-md\"");

WriteLiteral(">\r\n                        ویرایش اطلاعات متقاضی\r\n                    </button>\r\n" +
"                </div>\r\n            </div>\r\n            <hr");

WriteLiteral(" class=\"margin-bottom-5 margin-top-5\"");

WriteLiteral(" />\r\n            <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#baseInfo\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">اطلاعات پایه</a>\r\n                </li>\r\n                <li>\r\n                 " +
"   <a");

WriteLiteral(" href=\"#other\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">سایر اطلاعات</a>\r\n                </li>\r\n\r\n                <li>\r\n               " +
"     <a");

WriteLiteral(" href=\"#files\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">فایل های ضمیمه</a>\r\n                </li>\r\n            </ul>\r\n            <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"baseInfo\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 57 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 59 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 60 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 64 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 66 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 67 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 72 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.NationalCode, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 74 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.NationalCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 75 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.NationalCode, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 79 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BirthCertificateNumber, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 81 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.BirthCertificateNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 82 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthCertificateNumber, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 86 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 88 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.Gender, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 89 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 91 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.MarriageStatus, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 93 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.MarriageStatus, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 94 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.MarriageStatus, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 98 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BirthPlaceState, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 100 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.DropDownListFor(model => model.BirthPlaceState,
                            Model.StatesForBirthPlace, "انتخاب استان محل تولد", new
                            {
                                @class = "form-control cascade",
                                data_tofill = "BirthPlaceCity",
                                data_lable = "انتخاب شهر محل تولد",
                                data_selects = "BirthPlaceCity",
                                data_url = Url.Action(MVC.City.GetCities())
                            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 109 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthPlaceState, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 111 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BirthPlaceCity, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 113 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.DropDownListFor(model => model.BirthPlaceCity, Model.CitiesForBirthPlace, "انتخاب شهر محل تولد", new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 114 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthPlaceCity, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 118 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 120 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.BirthDate, MVC.Shared.Views.EditorTemplates.PersianDatePicker));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 121 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                    </div>\r\n                </div>\r" +
"\n                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"other\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 131 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.FatherName, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 133 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.FatherName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 134 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 138 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 140 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 141 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 145 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.CellphoneNumber, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 147 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.CellphoneNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 148 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.CellphoneNumber, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 152 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 154 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.PhoneNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 155 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 160 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.NumberIndispensable, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 162 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.NumberIndispensable));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 163 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.NumberIndispensable, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n\r\n " +
"                           <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 168 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.MilitaryStatus, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 170 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.MilitaryStatus, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 171 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.MilitaryStatus, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 173 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.MembershipType, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 175 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.MembershipType, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 176 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.MembershipType, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 180 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.ServedEndOn, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 182 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.ServedEndOn, MVC.Shared.Views.EditorTemplates.PersianDatePicker));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 183 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.ServedEndOn, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 187 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.Gilder, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 189 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.Gilder));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 190 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Gilder, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 194 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 196 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.Nationality));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 197 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                    </div>\r\n                </div>\r" +
"\n\r\n\r\n                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"files\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 209 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.CopyOfNationalCardFile, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 211 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.TextBoxFor(model => model.CopyOfNationalCardFile, new { type = "file", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"CopyOfNationalCardScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 14325), Tuple.Create("\"", 14425)
, Tuple.Create(Tuple.Create("", 14333), Tuple.Create("btn", 14333), true)
, Tuple.Create(Tuple.Create(" ", 14336), Tuple.Create("btn-primary", 14337), true)
, Tuple.Create(Tuple.Create("   ", 14348), Tuple.Create("btn-sm", 14351), true)
            
            #line 214 "..\..\Views\Applicant\Edit.cshtml"
                                                                                      , Tuple.Create(Tuple.Create(" ", 14357), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 14358), false)
);

WriteLiteral(">\r\n");

            
            #line 215 "..\..\Views\Applicant\Edit.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 215 "..\..\Views\Applicant\Edit.cshtml"
                                         if (Model.CopyOfNationalCardScan.HasValue())
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                            حذف فایل اسکن شده\r\n           " +
"                             ");

WriteLiteral("\r\n");

            
            #line 220 "..\..\Views\Applicant\Edit.cshtml"
                                        }
                                        else
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <i");

WriteLiteral(" class=\"fa fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                            افزودن اسکن\r\n                 " +
"                       ");

WriteLiteral("\r\n");

            
            #line 226 "..\..\Views\Applicant\Edit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </button>\r\n                                </" +
"div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 231 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.CopyOfBirthCertificateFile, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 233 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.TextBoxFor(model => model.CopyOfBirthCertificateFile, new { type = "file", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"CopyOfBirthCertificateScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 15880), Tuple.Create("\"", 15980)
, Tuple.Create(Tuple.Create("", 15888), Tuple.Create("btn", 15888), true)
, Tuple.Create(Tuple.Create(" ", 15891), Tuple.Create("btn-primary", 15892), true)
, Tuple.Create(Tuple.Create("   ", 15903), Tuple.Create("btn-sm", 15906), true)
            
            #line 236 "..\..\Views\Applicant\Edit.cshtml"
                                                                                          , Tuple.Create(Tuple.Create(" ", 15912), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 15913), false)
);

WriteLiteral(">\r\n");

            
            #line 237 "..\..\Views\Applicant\Edit.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 237 "..\..\Views\Applicant\Edit.cshtml"
                                         if (Model.CopyOfBirthCertificateScan.HasValue())
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                            حذف فایل اسکن شده\r\n           " +
"                             ");

WriteLiteral("\r\n");

            
            #line 242 "..\..\Views\Applicant\Edit.cshtml"
                                        }
                                        else
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <i");

WriteLiteral(" class=\"fa  fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                            افزودن اسکن\r\n                 " +
"                       ");

WriteLiteral("\r\n");

            
            #line 248 "..\..\Views\Applicant\Edit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </button>\r\n                                </" +
"div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 253 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 255 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.TextBoxFor(model => model.PhotoFile, new { type = "file", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"PhotoScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 17389), Tuple.Create("\"", 17489)
, Tuple.Create(Tuple.Create("", 17397), Tuple.Create("btn", 17397), true)
, Tuple.Create(Tuple.Create(" ", 17400), Tuple.Create("btn-primary", 17401), true)
, Tuple.Create(Tuple.Create("   ", 17412), Tuple.Create("btn-sm", 17415), true)
            
            #line 258 "..\..\Views\Applicant\Edit.cshtml"
                                                                         , Tuple.Create(Tuple.Create(" ", 17421), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 17422), false)
);

WriteLiteral(">\r\n");

            
            #line 259 "..\..\Views\Applicant\Edit.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 259 "..\..\Views\Applicant\Edit.cshtml"
                                         if (Model.PhotoScan.HasValue())
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                            حذف فایل اسکن شده\r\n           " +
"                             ");

WriteLiteral("\r\n");

            
            #line 264 "..\..\Views\Applicant\Edit.cshtml"
                                        }
                                        else
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                            <i");

WriteLiteral(" class=\"fa fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                            افزودن اسکن\r\n                 " +
"                       ");

WriteLiteral("\r\n");

            
            #line 270 "..\..\Views\Applicant\Edit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </button>\r\n                                </" +
"div>\r\n                            </div>\r\n                        </div>\r\n      " +
"              </div>\r\n                </div>\r\n            </div>\r\n        </div>" +
"\r\n    </div>\r\n");

            
            #line 280 "..\..\Views\Applicant\Edit.cshtml"
}

            
            #line default
            #line hidden
DefineSection("Menu", () => {

WriteLiteral("\r\n");

            
            #line 282 "..\..\Views\Applicant\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 282 "..\..\Views\Applicant\Edit.cshtml"
      Html.RenderPartial(MVC.Applicant.Views._ApplicantRelatedLinksBuilder, Model.Id);
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 285 "..\..\Views\Applicant\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 286 "..\..\Views\Applicant\Edit.cshtml"
Write(Scripts.Render("~/bundles/datePicker"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
