#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decision.Web.RazorHelpers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\RazorHelpers\NotyBuilder.cshtml"
    using Decision.Common.Noty;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class NotyBuilder : System.Web.WebPages.HelperPage
    {

#line 10 "..\..\RazorHelpers\NotyBuilder.cshtml"
public static System.Web.WebPages.HelperResult ShowNotyMessages(Noty notyInput)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 11 "..\..\RazorHelpers\NotyBuilder.cshtml"
 
    if (notyInput == null)
    {
        return;
    }



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <script>\r\n    $(function() {\r\n\r\n");


#line 20 "..\..\RazorHelpers\NotyBuilder.cshtml"
        

#line default
#line hidden

#line 20 "..\..\RazorHelpers\NotyBuilder.cshtml"
         foreach (var message in notyInput.NotyMessages)
            {
                

#line default
#line hidden

#line 62 "..\..\RazorHelpers\NotyBuilder.cshtml"
                                           


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            ");

WriteLiteralTo(__razor_helper_writer, "infoNoty(\'");


#line 63 "..\..\RazorHelpers\NotyBuilder.cshtml"
WriteTo(__razor_helper_writer, message.Message);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\');\r\n");


#line 64 "..\..\RazorHelpers\NotyBuilder.cshtml"
                }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n    });\r\n\r\n    </script>\r\n");


#line 69 "..\..\RazorHelpers\NotyBuilder.cshtml"


#line default
#line hidden
});

#line 69 "..\..\RazorHelpers\NotyBuilder.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
