#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Applicant\Edit.cshtml"
    using Decision.Common.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Applicant\Edit.cshtml"
    using Decision.Common.Helpers.Extentions;
    
    #line default
    #line hidden
    using Decision.Common.MVC;
    using Decision.Utility;
    using Decision.Web.HtmlHelpers;
    
    #line 3 "..\..\Views\Applicant\Edit.cshtml"
    using Decision.Web.RazorHelpers;
    
    #line default
    #line hidden
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Applicant/Edit.cshtml")]
    public partial class _Views_Applicant_Edit_cshtml : System.Web.Mvc.WebViewPage<Decision.ViewModel.Applicant.EditApplicantViewModel>
    {
        public _Views_Applicant_Edit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Applicant\Edit.cshtml"
  
    ViewBag.Title = "ویرایش متقاضی";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Applicant\Edit.cshtml"
 using (Html.BeginForm(MVC.Applicant.Edit(), FormMethod.Post, new { role = "form", @class = "form-horizontal", autocomplete = "off", id = "editApplicantForm", enctype = "multipart/form-data" }))
{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Applicant\Edit.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Applicant\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.HiddenFor(model => model.PhotoScan));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Applicant\Edit.cshtml"
                                             
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.HiddenFor(model => model.CopyOfBirthCertificateScan));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Applicant\Edit.cshtml"
                                                              
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Applicant\Edit.cshtml"
Write(Html.HiddenFor(model => model.CopyOfNationalCardScan));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Applicant\Edit.cshtml"
                                                          



            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 21 "..\..\Views\Applicant\Edit.cshtml"
               Write(Html.HelpAlert(Url.Content("~/Content/Images/lightbulb.png"),
                    "در صورت عمل نکردن دکمه ثبت،توجه داشته باشید که تمام اطلاعات را در تمام تب های موجود صحیح وارد کرده باشید",

         "برای فایل های ضمیمه مربوط به متقاضی از امکان آپلود تصاویر یا اسکن  میتوانید بهره مند شوید.",
                    "دقت کنید در صورت انتخاب فایل جدید،جایگزین فایل های جدید خواهد شد"
           ));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-md-1\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'editApplicantForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-md\"");

WriteLiteral(">\r\n                        ذخیره تغییرات انجام شده\r\n                    </button>" +
"\r\n                </div>\r\n            </div>\r\n            <hr");

WriteLiteral(" class=\"margin-bottom-5 margin-top-5\"");

WriteLiteral(" />\r\n            <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#baseInfo\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">اطلاعات پایه</a>\r\n                </li>\r\n                <li>\r\n                 " +
"   <a");

WriteLiteral(" href=\"#bank\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">اطلاعات بانکی</a>\r\n                </li>\r\n                <li>\r\n                " +
"    <a");

WriteLiteral(" href=\"#certificate\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">اطلاعات شغلی</a>\r\n                </li>\r\n                <li>\r\n                 " +
"   <a");

WriteLiteral(" href=\"#trainingCourse\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">دوره کارآموزی</a>\r\n                </li>\r\n                <li>\r\n                " +
"    <a");

WriteLiteral(" href=\"#files\"");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">فایل های ضمیمه</a>\r\n                </li>\r\n            </ul>\r\n            <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"baseInfo\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 61 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 63 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 64 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 68 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 70 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 71 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 75 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.PersonnelCode, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 77 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.PersonnelCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 78 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.PersonnelCode, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 82 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.NationalCode, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 84 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.NationalCode));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 85 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.NationalCode, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 89 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BirthCertificateNumber, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 91 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.BirthCertificateNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 92 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthCertificateNumber, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 96 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 98 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.Gender, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 99 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 101 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.MarriageStatus, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 103 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.MarriageStatus, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 104 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.MarriageStatus, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 108 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BirthPlaceState, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 110 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.DropDownListFor(model => model.BirthPlaceState,
                            Model.StatesForBirthPlace, "انتخاب استان محل تولد", new
                            {
                                @class = "form-control cascade",
                                data_tofill = "BirthPlaceCity",
                                data_lable = "انتخاب شهر محل تولد",
                                data_selects = "BirthPlaceCity",
                                data_url = Url.Action(MVC.City.GetCities())
                            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 119 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthPlaceState, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 121 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BirthPlaceCity, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 123 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.DropDownListFor(model => model.BirthPlaceCity, Model.CitiesForBirthPlace, "انتخاب شهر محل تولد", new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 124 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthPlaceCity, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 128 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 130 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.BirthDate, MVC.Shared.Views.EditorTemplates.PersianDatePicker));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 131 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                    </div>\r\n                </div>\r" +
"\n                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"bank\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 141 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BankName, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 143 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.BankName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 144 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BankName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 148 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.BankBranch, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 150 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.BankBranch));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 151 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.BankBranch, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 155 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.AccountNumber, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 157 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxFor(model => model.AccountNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 158 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.AccountNumber, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                    </div>\r\n                </div>\r" +
"\n                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"certificate\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 168 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.TrainingGPA, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 170 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.EditorFor(model => model.TrainingGPA));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 171 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TrainingGPA, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 173 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.TrainigGrade, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 175 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForLtr(model => model.TrainigGrade));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 176 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TrainigGrade, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 180 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.CollegiateOrder, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 182 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForNumber(model => model.CollegiateOrder));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 183 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.CollegiateOrder, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 185 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.OccupationalGroup, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 187 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForNumber(model => model.OccupationalGroup));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 188 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.OccupationalGroup, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 192 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.OfficialYears, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 194 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForNumber(model => model.OfficialYears));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 195 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.OfficialYears, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 197 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.CollegiateYears, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 199 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.NoAutoCompleteTextBoxForNumber(model => model.CollegiateYears));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 200 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.CollegiateYears, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 204 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.PositionId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 206 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.DropDownListFor(model => model.PositionId, Model.Positions, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 207 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.PositionId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                               \r\n      " +
"                          <div");

WriteLiteral(" class=\"col-md-4 col-md-offset-2\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("                                    ");

            
            #line 212 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.CheckBoxFor(model => model.IsClothed, new { @class = "checkbox-inline" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 213 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.LabelFor(a => a.IsClothed, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                </div>\r\n                            </div>\r\n " +
"                       </div>\r\n                    </div>\r\n                </div" +
">\r\n                <div");

WriteLiteral(" id=\"trainingCourse\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 224 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.TrainingCenterState, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 226 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.DropDownListFor(model => model.TrainingCenterState, Model.StatesForTrainingCeneter, "انتخاب", new
                   {
                       @class = "form-control cascade",
                       data_tofill = "TrainingCenterCity",
                       data_lable = "انتخاب",
                       data_selects = "TrainingCenterCity,TrainingCenterId,TrainingCourseId",
                       data_url = Url.Action(MVC.City.GetCities())
                   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 234 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TrainingCenterState, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 236 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.TrainingCenterCity, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 238 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.DropDownListFor(model => model.TrainingCenterCity, Model.CitiesForTrainingCeneter, "انتخاب", new
                   {
                       @class = "form-control cascade",
                       data_tofill = "TrainingCenterId",
                       data_lable = "انتخاب",
                       data_selects = "TrainingCenterId,TrainingCourseId",
                       data_url = Url.Action(MVC.TrainingCenter.GetCenters())
                   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 246 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TrainingCenterCity, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                         <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 250 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.TrainingCenterId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 252 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.DropDownListFor(model => model.TrainingCenterId, Model.TrainingCenters, "انتخاب", new
                   {
                       @class = "form-control cascade",
                       data_tofill = "TrainingCourseId",
                       data_lable = "انتخاب",
                       data_selects = "TrainingCourseId",
                       data_url = Url.Action(MVC.TrainingCourse.GetCourses())
                   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 260 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TrainingCenterId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

WriteLiteral("                                ");

            
            #line 262 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.TrainingCourseId, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 264 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.DropDownListFor(model => model.TrainingCourseId, Model.TrainingCourses, "انتخاب", new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 265 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.ValidationMessageFor(model => model.TrainingCourseId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                    </div>\r\n                </div>\r" +
"\n                <div");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(" id=\"files\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 275 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.CopyOfNationalCardFile, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 277 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.TextBoxFor(model => model.CopyOfNationalCardFile, new { type = "file", @class = "form-control " }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"CopyOfNationalCardScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 19063), Tuple.Create("\"", 19163)
, Tuple.Create(Tuple.Create("", 19071), Tuple.Create("btn", 19071), true)
, Tuple.Create(Tuple.Create(" ", 19074), Tuple.Create("btn-primary", 19075), true)
, Tuple.Create(Tuple.Create("   ", 19086), Tuple.Create("btn-sm", 19089), true)
            
            #line 280 "..\..\Views\Applicant\Edit.cshtml"
                                                                                      , Tuple.Create(Tuple.Create(" ", 19095), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 19096), false)
);

WriteLiteral(">\r\n");

            
            #line 281 "..\..\Views\Applicant\Edit.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 281 "..\..\Views\Applicant\Edit.cshtml"
                                         if (Model.CopyOfNationalCardScan.HasValue())
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                حذف فایل اسکن شده\r\n                       " +
"                 ");

WriteLiteral("\r\n");

            
            #line 286 "..\..\Views\Applicant\Edit.cshtml"
                                        }
                                        else
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                افزودن اسکن\r\n                             " +
"           ");

WriteLiteral("\r\n");

            
            #line 292 "..\..\Views\Applicant\Edit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </button>\r\n                                </" +
"div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 297 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.CopyOfBirthCertificateFile, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 299 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.TextBoxFor(model => model.CopyOfBirthCertificateFile, new { type = "file", @class = "form-control " }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"CopyOfBirthCertificateScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 20571), Tuple.Create("\"", 20671)
, Tuple.Create(Tuple.Create("", 20579), Tuple.Create("btn", 20579), true)
, Tuple.Create(Tuple.Create(" ", 20582), Tuple.Create("btn-primary", 20583), true)
, Tuple.Create(Tuple.Create("   ", 20594), Tuple.Create("btn-sm", 20597), true)
            
            #line 302 "..\..\Views\Applicant\Edit.cshtml"
                                                                                          , Tuple.Create(Tuple.Create(" ", 20603), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 20604), false)
);

WriteLiteral(">\r\n");

            
            #line 303 "..\..\Views\Applicant\Edit.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 303 "..\..\Views\Applicant\Edit.cshtml"
                                         if (Model.CopyOfBirthCertificateScan.HasValue())
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                حذف فایل اسکن شده\r\n                       " +
"                 ");

WriteLiteral("\r\n");

            
            #line 308 "..\..\Views\Applicant\Edit.cshtml"
                                        }
                                        else
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa  fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                افزودن اسکن\r\n                             " +
"           ");

WriteLiteral("\r\n");

            
            #line 314 "..\..\Views\Applicant\Edit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </button>\r\n                                </" +
"div>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 319 "..\..\Views\Applicant\Edit.cshtml"
                           Write(Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 321 "..\..\Views\Applicant\Edit.cshtml"
                               Write(Html.TextBoxFor(model => model.PhotoFile, new { type = "file", @class = "form-control " }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" data-type=\"image\"");

WriteLiteral(" data-container=\"PhotoScan\"");

WriteAttribute("class", Tuple.Create(" class=\"", 22033), Tuple.Create("\"", 22133)
, Tuple.Create(Tuple.Create("", 22041), Tuple.Create("btn", 22041), true)
, Tuple.Create(Tuple.Create(" ", 22044), Tuple.Create("btn-primary", 22045), true)
, Tuple.Create(Tuple.Create("   ", 22056), Tuple.Create("btn-sm", 22059), true)
            
            #line 324 "..\..\Views\Applicant\Edit.cshtml"
                                                                         , Tuple.Create(Tuple.Create(" ", 22065), Tuple.Create<System.Object, System.Int32>(Model.CopyOfNationalCardScan.HasValue() ? "scan-remove" : "scan"
            
            #line default
            #line hidden
, 22066), false)
);

WriteLiteral(">\r\n");

            
            #line 325 "..\..\Views\Applicant\Edit.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 325 "..\..\Views\Applicant\Edit.cshtml"
                                         if (Model.PhotoScan.HasValue())
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-remove\"");

WriteLiteral("></i>\r\n                                حذف فایل اسکن شده\r\n                       " +
"                 ");

WriteLiteral("\r\n");

            
            #line 330 "..\..\Views\Applicant\Edit.cshtml"
                                        }
                                        else
                                        {
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <i");

WriteLiteral(" class=\"fa fa-file-photo-o\"");

WriteLiteral("></i>\r\n                                افزودن اسکن\r\n                             " +
"           ");

WriteLiteral("\r\n");

            
            #line 336 "..\..\Views\Applicant\Edit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </button>\r\n                                </" +
"div>\r\n                            </div>\r\n                        </div>\r\n      " +
"              </div>\r\n                </div>\r\n            </div>\r\n        </div>" +
"\r\n    </div>\r\n");

            
            #line 346 "..\..\Views\Applicant\Edit.cshtml"
}

            
            #line default
            #line hidden
DefineSection("Menu", () => {

WriteLiteral("\r\n");

            
            #line 348 "..\..\Views\Applicant\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 348 "..\..\Views\Applicant\Edit.cshtml"
      Html.RenderPartial(MVC.Applicant.Views._ApplicantRelatedLinksBuilder, Model.Id);
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 351 "..\..\Views\Applicant\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 352 "..\..\Views\Applicant\Edit.cshtml"
Write(Scripts.Render("~/bundles/datePicker"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
